# Generated by Django 5.0.6 on 2024-05-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0002_alter_persona_celular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="Celular",
            new_name="celular",
        ),
        migrations.RenameField(
            model_name="persona",
            old_name="Correo",
            new_name="correo",
        ),
    ]
